
package clients.wsimports.eu;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PlayerServiceImplementationService", targetNamespace = "http://playerservices/", wsdlLocation = "http://localhost:8080/eu?wsdl")
public class PlayerServiceImplementationService
    extends Service
{

    private final static URL PLAYERSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException PLAYERSERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName PLAYERSERVICEIMPLEMENTATIONSERVICE_QNAME = new QName("http://playerservices/", "PlayerServiceImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/eu?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PLAYERSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        PLAYERSERVICEIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public PlayerServiceImplementationService() {
        super(__getWsdlLocation(), PLAYERSERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public PlayerServiceImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PLAYERSERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public PlayerServiceImplementationService(URL wsdlLocation) {
        super(wsdlLocation, PLAYERSERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public PlayerServiceImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PLAYERSERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public PlayerServiceImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PlayerServiceImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PlayerServiceImplementation
     */
    @WebEndpoint(name = "PlayerServiceImplementationPort")
    public PlayerServiceImplementation getPlayerServiceImplementationPort() {
        return super.getPort(new QName("http://playerservices/", "PlayerServiceImplementationPort"), PlayerServiceImplementation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PlayerServiceImplementation
     */
    @WebEndpoint(name = "PlayerServiceImplementationPort")
    public PlayerServiceImplementation getPlayerServiceImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://playerservices/", "PlayerServiceImplementationPort"), PlayerServiceImplementation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PLAYERSERVICEIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw PLAYERSERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return PLAYERSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
