
package clients.wsimports.eu;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PlayerServiceEUImplementationService", targetNamespace = "http://eu.playerservices/", wsdlLocation = "http://localhost:8080/eu?wsdl")
public class PlayerServiceEUImplementationService
    extends Service
{

    private final static URL PLAYERSERVICEEUIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException PLAYERSERVICEEUIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName PLAYERSERVICEEUIMPLEMENTATIONSERVICE_QNAME = new QName("http://eu.playerservices/", "PlayerServiceEUImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/eu?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PLAYERSERVICEEUIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        PLAYERSERVICEEUIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public PlayerServiceEUImplementationService() {
        super(__getWsdlLocation(), PLAYERSERVICEEUIMPLEMENTATIONSERVICE_QNAME);
    }

    public PlayerServiceEUImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PLAYERSERVICEEUIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public PlayerServiceEUImplementationService(URL wsdlLocation) {
        super(wsdlLocation, PLAYERSERVICEEUIMPLEMENTATIONSERVICE_QNAME);
    }

    public PlayerServiceEUImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PLAYERSERVICEEUIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public PlayerServiceEUImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PlayerServiceEUImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PlayerServiceEUImplementation
     */
    @WebEndpoint(name = "PlayerServiceEUImplementationPort")
    public PlayerServiceEUImplementation getPlayerServiceEUImplementationPort() {
        return super.getPort(new QName("http://eu.playerservices/", "PlayerServiceEUImplementationPort"), PlayerServiceEUImplementation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PlayerServiceEUImplementation
     */
    @WebEndpoint(name = "PlayerServiceEUImplementationPort")
    public PlayerServiceEUImplementation getPlayerServiceEUImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://eu.playerservices/", "PlayerServiceEUImplementationPort"), PlayerServiceEUImplementation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PLAYERSERVICEEUIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw PLAYERSERVICEEUIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return PLAYERSERVICEEUIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
