
package clients.wsimports.as;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PlayerServiceASImplementation", targetNamespace = "http://as.playerservices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PlayerServiceASImplementation {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createPlayerAccount", targetNamespace = "http://as.playerservices/", className = "clients.wsimports.as.CreatePlayerAccount")
    @ResponseWrapper(localName = "createPlayerAccountResponse", targetNamespace = "http://as.playerservices/", className = "clients.wsimports.as.CreatePlayerAccountResponse")
    @Action(input = "http://as.playerservices/PlayerServiceASImplementation/createPlayerAccountRequest", output = "http://as.playerservices/PlayerServiceASImplementation/createPlayerAccountResponse")
    public String createPlayerAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "playerSignIn", targetNamespace = "http://as.playerservices/", className = "clients.wsimports.as.PlayerSignIn")
    @ResponseWrapper(localName = "playerSignInResponse", targetNamespace = "http://as.playerservices/", className = "clients.wsimports.as.PlayerSignInResponse")
    @Action(input = "http://as.playerservices/PlayerServiceASImplementation/playerSignInRequest", output = "http://as.playerservices/PlayerServiceASImplementation/playerSignInResponse")
    public String playerSignIn(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "playerSignOut", targetNamespace = "http://as.playerservices/", className = "clients.wsimports.as.PlayerSignOut")
    @ResponseWrapper(localName = "playerSignOutResponse", targetNamespace = "http://as.playerservices/", className = "clients.wsimports.as.PlayerSignOutResponse")
    @Action(input = "http://as.playerservices/PlayerServiceASImplementation/playerSignOutRequest", output = "http://as.playerservices/PlayerServiceASImplementation/playerSignOutResponse")
    public String playerSignOut(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transferAccount", targetNamespace = "http://as.playerservices/", className = "clients.wsimports.as.TransferAccount")
    @ResponseWrapper(localName = "transferAccountResponse", targetNamespace = "http://as.playerservices/", className = "clients.wsimports.as.TransferAccountResponse")
    @Action(input = "http://as.playerservices/PlayerServiceASImplementation/transferAccountRequest", output = "http://as.playerservices/PlayerServiceASImplementation/transferAccountResponse")
    public String transferAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "adminSignIn", targetNamespace = "http://as.playerservices/", className = "clients.wsimports.as.AdminSignIn")
    @ResponseWrapper(localName = "adminSignInResponse", targetNamespace = "http://as.playerservices/", className = "clients.wsimports.as.AdminSignInResponse")
    @Action(input = "http://as.playerservices/PlayerServiceASImplementation/adminSignInRequest", output = "http://as.playerservices/PlayerServiceASImplementation/adminSignInResponse")
    public String adminSignIn(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "adminSignOut", targetNamespace = "http://as.playerservices/", className = "clients.wsimports.as.AdminSignOut")
    @ResponseWrapper(localName = "adminSignOutResponse", targetNamespace = "http://as.playerservices/", className = "clients.wsimports.as.AdminSignOutResponse")
    @Action(input = "http://as.playerservices/PlayerServiceASImplementation/adminSignOutRequest", output = "http://as.playerservices/PlayerServiceASImplementation/adminSignOutResponse")
    public String adminSignOut(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPlayerStatus", targetNamespace = "http://as.playerservices/", className = "clients.wsimports.as.GetPlayerStatus")
    @ResponseWrapper(localName = "getPlayerStatusResponse", targetNamespace = "http://as.playerservices/", className = "clients.wsimports.as.GetPlayerStatusResponse")
    @Action(input = "http://as.playerservices/PlayerServiceASImplementation/getPlayerStatusRequest", output = "http://as.playerservices/PlayerServiceASImplementation/getPlayerStatusResponse")
    public String getPlayerStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "suspendAccount", targetNamespace = "http://as.playerservices/", className = "clients.wsimports.as.SuspendAccount")
    @ResponseWrapper(localName = "suspendAccountResponse", targetNamespace = "http://as.playerservices/", className = "clients.wsimports.as.SuspendAccountResponse")
    @Action(input = "http://as.playerservices/PlayerServiceASImplementation/suspendAccountRequest", output = "http://as.playerservices/PlayerServiceASImplementation/suspendAccountResponse")
    public String suspendAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

}
