
package clients.wsimports.as;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PlayerServiceASImplementationService", targetNamespace = "http://as.playerservices/", wsdlLocation = "http://localhost:8080/as?wsdl")
public class PlayerServiceASImplementationService
    extends Service
{

    private final static URL PLAYERSERVICEASIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException PLAYERSERVICEASIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName PLAYERSERVICEASIMPLEMENTATIONSERVICE_QNAME = new QName("http://as.playerservices/", "PlayerServiceASImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/as?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PLAYERSERVICEASIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        PLAYERSERVICEASIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public PlayerServiceASImplementationService() {
        super(__getWsdlLocation(), PLAYERSERVICEASIMPLEMENTATIONSERVICE_QNAME);
    }

    public PlayerServiceASImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PLAYERSERVICEASIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public PlayerServiceASImplementationService(URL wsdlLocation) {
        super(wsdlLocation, PLAYERSERVICEASIMPLEMENTATIONSERVICE_QNAME);
    }

    public PlayerServiceASImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PLAYERSERVICEASIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public PlayerServiceASImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PlayerServiceASImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PlayerServiceASImplementation
     */
    @WebEndpoint(name = "PlayerServiceASImplementationPort")
    public PlayerServiceASImplementation getPlayerServiceASImplementationPort() {
        return super.getPort(new QName("http://as.playerservices/", "PlayerServiceASImplementationPort"), PlayerServiceASImplementation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PlayerServiceASImplementation
     */
    @WebEndpoint(name = "PlayerServiceASImplementationPort")
    public PlayerServiceASImplementation getPlayerServiceASImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://as.playerservices/", "PlayerServiceASImplementationPort"), PlayerServiceASImplementation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PLAYERSERVICEASIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw PLAYERSERVICEASIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return PLAYERSERVICEASIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
